version: "3"

services:
  alabuga:
      build: .
      env_file:
        - docker.env
      ports:
        - "5000:5000"
      networks:
        - alabuga
        
networks:
  alabuga:
    driver: bridge